### ISSUE TITLE
HTML did not run (minor issues)

### ISSUE THREAD

**Issue by jetic83** [slntRohit/OpenSeadragonThreejsOverlay#3]
Hi,

the demo works well!

But when downloading this repo and double click on index.html, I had to change two things to get it run (maybe it is also my PC, or the not-use of a web server)
- I had to replace `<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>` by `<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>`
- I had to rewrite and resave the line `this.resourcePath = this.resourcePath || path;` in three.js, since Chrome reported a wired encoding character (||Â path) in that line and THREE was not defined therefore.

Thanks again for this nice plugin!

**Comment by r10a** [comment]
@jetic83 Thank you for checking out the plugin. I can confirm after running on multiple laptops that this is not really an issue with the code. I would recommend using the [live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) plugin in vscode to view index.html. It should load flawlessly.

Closing this issue for now. Let me know if the issue still persists.
